### ISSUE TITLE
Warning generated when including this nuget to project

### ISSUE THREAD

**Issue by Cekdisout** [mjuen/Notifications.Wpf.Core#1]
When using this nuget withing strongly named assembly project it generates warning that Notifications.Wpf.Core assembly does not have strong name.
Warning CS8002: Referenced assembly 'Notifications.Wpf.Core, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

Can you sign this nuget with strong name?

**Comment by mjuen** [comment]
Should now be fixed with version 1.3.2.

**Comment by Cekdisout** [comment]
Thanks! :)
