### ISSUE TITLE
Warning toast is very difficult to read

### ISSUE THREAD

**Issue by Mgamerz** [mjuen/Notifications.Wpf.Core#2]
Hi, thanks for forking this and making it with work with .NET Core. I forked the project and am playing around with ways to improve the accessibility of the toasts. For example here are two toasts my app shows:

![image](https://user-images.githubusercontent.com/2738836/97752574-daf9ad80-1ab9-11eb-8dd5-5a946ac15d88.png)

The blue one is mostly readable, the yellow one I find pretty difficult. I do want the yellow background though, as this is a more important message.

I fooled around in Generic.xaml and found the Opacity is set to 0.8 on the message. I changed it to 1 which improved the accessibilility somewhat.

![image](https://user-images.githubusercontent.com/2738836/97752821-6410e480-1aba-11eb-8618-8b66d6c8cd47.png)

However the white on yellow is still hard to read. I added a dropshadow to the text, which helped further, but it also clasehd a bit with the visual style.
![image](https://user-images.githubusercontent.com/2738836/97753049-be11aa00-1aba-11eb-9d0c-6aa292936943.png)

This was done by changing the items near line 44 in Generic.xaml:
```
                        <DockPanel Grid.Column="1">
                            <TextBlock DockPanel.Dock="Top" Text="{Binding Title}" FontWeight="Medium" TextTrimming="CharacterEllipsis" >
                                <TextBlock.Effect>
                                    <DropShadowEffect ShadowDepth="1" RenderingBias="Performance" Color="Black"/>
                                </TextBlock.Effect>
                            </TextBlock>
                            <TextBlock Text="{Binding Message}" TextWrapping="Wrap" Opacity="1" Margin="0,0,12,0">
                                <TextBlock.Effect>
                                    <DropShadowEffect ShadowDepth="1" RenderingBias="Performance" Color="Black"/>
                                </TextBlock.Effect>
                            </TextBlock>
                        </DockPanel>
```

I'm not sure how you could tweak the yellow one to be more legible. This is an improvement but a bit of a style change for the interface, so I'm not sure this is what you'd want to include as the only option.

The final solution I had looks like this):
![image](https://user-images.githubusercontent.com/2738836/97753855-17c6a400-1abc-11eb-9c57-fd46c9bbd218.png)

I'd be interested in submitting a PR (https://github.com/Mgamerz/Notifications.Wpf.Core/commit/620a2997f8ff4e30eaae48ca2464e4746e512659) if this is something you'd like to have in the project. I'm not too well versed in templating so I'm not sure how to make this user configurable...

**Comment by mjuen** [comment]
Hi @Mgamerz,

thanks for your input! For now I am leaving the default style as it is but I have added an example of custom styling based on your issue to the sample project and created a section in the README to point to it. As it is quite easy to tweak the default styles I think everyone should decide for himself what styles to use and adjust them to their needs accordingly.
